application:
  title: Gestione Corsi
  version: 1.0
spring:
  flyway:
    locations: classpath:db/migration/h2
  h2:
    console.enabled: true
  datasource:
    hikari:
      pool-name: "Gestione corsi"
      maximum-pool-size: 20
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
    url: jdbc:h2:file:./db/gestione-corsi
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      show-sql: true
logging:
  file:
    name: logs/courses.log
  logback:
    rollingpolicy:
      file-name-pattern: courses%d{yyyy-MM-dd}.%i.log.tar.gz
      max-file-size: 10MB
      total-size-cap: 200MB
      max-history: 10
  level:
    org:
      springframework:
        security: TRACE
server:
  port: 9090
  servlet:
    context-path: /gs
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
management:
  endpoints:
    web:
      exposure:
        include: "*"